spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo-springboot?serverTimezone=Asia/Taipei
    username: root
    password: 11256040

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /api
  api-docs:
    # OpenAPI 資料的後端路徑
    path: /v3/api-docs
